org: gerhardfreiberg
service: api-web-scraping

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::980106331918:role/LabRole

functions:
  scrape_sismos:
    handler: scrap_sismos.lambda_handler
    package:
      include:
        - ./**
    events:
      - http:
          path: /scrape/sismos
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    SismosReportados:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SismosReportados
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
